# tasks file
---
- name: create (profile) directories
  ansible.builtin.file:
    path: "{{ duply_backup_profile_directory }}/{{ item.key }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  with_dict: "{{ duply_backup_profiles }}"
  tags:
    - duply-backup-configuration-profile-directories

- name: configure configuration files
  ansible.builtin.template:
    src: etc/duply/conf.j2
    dest: "{{ duply_backup_profile_directory }}/{{ item.key }}/conf"
    owner: root
    group: root
    mode: 0600
  with_dict: "{{ duply_backup_profiles }}"
  tags:
    - duply-backup-configuration-profile-conf

- name: remove obsolete pre scripts
  ansible.builtin.file:
    path: "{{ duply_backup_profile_directory }}/{{ item.key }}/pre"
    state: absent
  with_dict: "{{ duply_backup_profiles }}"
  when: (item.value.pre is not defined or not item.value.pre) or (item.value.tpre is not defined or not item.value.tpre)
  tags:
    - duply-backup-configuration-profile-pre

- name: copy pre scripts
  ansible.builtin.copy:
    src: "{{ item.value.pre }}"
    dest: "{{ duply_backup_profile_directory }}/{{ item.key }}/pre"
    owner: root
    group: root
    mode: 0700
  with_dict: "{{ duply_backup_profiles }}"
  when:
    - item.value.pre is defined
    - item.value.pre
  tags:
    - duply-backup-configuration-profile-pre

- name: template dynamic pre scripts
  ansible.builtin.template:
    src: "{{ item.value.tpre }}.j2"
    dest: "{{ duply_backup_profile_directory }}/{{ item.key }}/pre"
    owner: root
    group: root
    mode: 0700
  with_dict: "{{ duply_backup_profiles }}"
  when:
    - item.value.tpre is defined
    - item.value.tpre
    # Don't install templated version if static version is defined
    - item.value.pre is not defined
  tags:
    - duply-backup-configuration-profile-pre

- name: remove obsolete post scripts
  ansible.builtin.file:
    path: "{{ duply_backup_profile_directory }}/{{ item.key }}/post"
    state: absent
  with_dict: "{{ duply_backup_profiles }}"
  when: (item.value.post is not defined or not item.value.post) or (item.value.tpost is not defined or not item.value.tpost)
  tags:
    - duply-backup-configuration-profile-post

- name: copy post scripts
  ansible.builtin.copy:
    src: "{{ item.value.post }}"
    dest: "{{ duply_backup_profile_directory }}/{{ item.key }}/post"
    owner: root
    group: root
    mode: 0700
  with_dict: "{{ duply_backup_profiles }}"
  when:
    - item.value.post is defined
    - item.value.post
  tags:
    - duply-backup-configuration-profile-post

- name: template dynamic post scripts
  ansible.builtin.template:
    src: "{{ item.value.tpost }}.j2"
    dest: "{{ duply_backup_profile_directory }}/{{ item.key }}/post"
    owner: root
    group: root
    mode: 0700
  with_dict: "{{ duply_backup_profiles }}"
  when:
    - item.value.tpost is defined
    - item.value.tpost
    # Don't install templated version if static version is defined
    - item.post is not defined
  tags:
    - duply-backup-configuration-profile-post

- name: configure exclude files
  ansible.builtin.template:
    src: etc/duply/exclude.j2
    dest: "{{ duply_backup_profile_directory }}/{{ item.key }}/exclude"
    owner: root
    group: root
    mode: 0600
  with_dict: "{{ duply_backup_profiles }}"
  tags:
    - duply-backup-configuration-profile-exclude
