# tasks file
---
- name: create (lock) directory
  ansible.builtin.file:
    path: "{{ duply_backup_lock_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - duply-backup-gpg-directory

- name: import public keys
  ansible.builtin.shell: >
    echo '{{ lookup('file', item) }}' | gpg --import && touch {{ duply_backup_lock_directory }}/{{ item | basename }}
  args:
    creates: "{{ duply_backup_lock_directory }}/{{ item | basename }}"
  with_items: "{{ duply_backup_gpg_pub_keys }}"
  tags:
    - duply-backup-gpg-pub-import

- name: import ownertrusts
  ansible.builtin.shell: >
    echo '{{ lookup('file', item) }}' | gpg --import-ownertrust && touch {{ duply_backup_lock_directory }}/{{ item | basename }}
  args:
    creates: "{{ duply_backup_lock_directory }}/{{ item | basename }}"
  notify: update trustdb
  with_items: "{{ duply_backup_gpg_ownertrusts }}"
  tags:
    - duply-backup-gpg-ownertrust-import

- name: import private keys
  ansible.builtin.shell: >
    echo '{{ lookup('file', item) }}' | gpg --allow-secret-key-import --batch --import && touch {{ duply_backup_lock_directory }}/{{ item | basename }}
  args:
    creates: "{{ duply_backup_lock_directory }}/{{ item | basename }}"
  with_items: "{{ duply_backup_gpg_sec_keys }}"
  tags:
    - duply-backup-gpg-sec-import
