# tasks file
---
- ansible.builtin.include: configuration.yml
  tags:
    - configuration
    - duply-backup
    - duply-backup-configuration

- ansible.builtin.include: gpg.yml
  tags:
    - configuration
    - duply-backup
    - duply-backup-gpg

- ansible.builtin.include: jobs.yml
  tags:
    - configuration
    - duply-backup
    - duply-backup-jobs
