# tasks file
---
- name: configuration
  ansible.builtin.import_tasks: configuration.yml
  tags:
    - configuration
    - duply-backup
    - duply-backup-configuration

- name: gpg
  ansible.builtin.import_tasks: gpg.yml
  tags:
    - configuration
    - duply-backup
    - duply-backup-gpg

- name: jobs
  ansible.builtin.import_tasks: jobs.yml
  tags:
    - configuration
    - duply-backup
    - duply-backup-jobs
